---
# tasks file for setup_jenkins_master
# Restore backup from github repositories
# Conections Master with Nodes

# Configuration DNS for possibility using internet connection in own cloud system
- name: Confige DNS
  copy: src=/home/vitalii/ansible/roles/setup_jenkins_master/files/resolv.conf dest=/etc/

# Installing necessary tools for install Jenkins on this machine
- name: Install yum
  yum:
    name:
      - wget
      - java-1.8.0-openjdk
      - git

# Next steps used for installing Jenkins master on the machine
- name: Download jenkins.repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

- name: Start & Enable Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: Open Firewall Port
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: true

# Next steps used for restoring backup our Jenkins with all configurations and pipelines if it is not primary setup Jenkins
- name: Remove directory
  file:
    path: /var/lib/jenkins
    state: absent

- name: Create directory for backup jenkins
  file:
    path: /var/lib/jenkins
    mode: 0755
    owner: jenkins
    group: jenkins
    state: directory

- name: Restore Jenkins from backup
  ansible.builtin.git:
    repo: https://github.com/VitaliiStorozh/backup.git
    dest: /var/lib/jenkins
    clone: yes
    update: no

- name: Change owner directory Jenkins
  file: dest=/var/lib/jenkins owner=jenkins group=jenkins mode=0775 recurse=yes

# Connect Nodes to the master if it necessary
- name: Change ip for Nodes
  ansible.builtin.replace:
    path: /var/lib/jenkins/nodes/Node1/config.xml
    regexp: '\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    replace: "{{ hostvars['jenkins-slave']['ansible_host']}}"


- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted
