#----------------------------------------------
#
# Task for create folders and files
#
# Created by Vitalii Storozh
#
#----------------------------------------------

---
  - name: My Super Playbook
    hosts: all
    become: yes

    vars:
      mytext: "Hello from Vitalii"

    tasks:
      - name: Ping test
        ping:

      - include: create_folders.yml

      - include: create_files.yml mytext="Hello from Kyiv"
