---
- name: Install Jenkins Master
  hosts: all
  gather_facts: false
  become: true
  vars: # bcname is name backup file
    bcname: jenkinsm-12-Mar-2021.tgz
  tasks:
    
    - block: # =======Block for BCP======
        - name: Copying the file
          fetch:
            src: /mnt/sdb/bcp/jmaster/{{bcname}}
            dest: /tmp/
            flat: yes
      when: inventory_hostname == "bcp"
    
    - block: # =======Block for MASTER======
        - name: Install yum GIT JAVA WGET
          yum:
            name:
              - wget
              - nano
              - java-1.8.0-openjdk
              - git

        - name: Download jenkins.repo
          get_url:
            url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
            dest: /etc/yum.repos.d/jenkins.repo

        - name: Import Jenkins Key
          rpm_key:
            state: present
            key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

        - name: Install Jenkins
          yum:
            name: jenkins
            state: present

        - name: Start & Enable Jenkins
          systemd:
            name: jenkins
            state: started
            enabled: true

        - name: Open Firewall Port
          firewalld:
            zone: public
            port: 8080/tcp
            permanent: true
            state: enabled
            immediate: true

        - name: Sleep for 30 seconds and continue with play
          wait_for: timeout=30

        - name: Restore
          copy: src=/tmp/{{bcname}} dest=/tmp/ 
    
        - name: Sopped Jenkins
          systemd:
            name: jenkins
            state: stopped    

        - name: Restore Jenkins
          ansible.builtin.unarchive:
            src: /tmp/{{bcname}}
            dest: /
      
        - name: Start Jenkins
          systemd:
            name: jenkins
            state: started
      when: "{{ inventory_hostname == 'master' }}"
