---
- name: Install Jenkins Master
  hosts: slave
  gather_facts: false
  become: true
  tasks:
    - name: Install yum
      yum:
        name:
          - wget
          - nano
          - java-1.8.0-openjdk
          - git

    - name: Download go.repo
      get_url:
        url: https://mirror.go-repo.io/centos/go-repo.repo
        dest: /etc/yum.repos.d/go-repo.repo

    - name: Import Key
      rpm_key:
        state: present
        key: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO

    - name: Install GO
      yum:
        name: golang
        state: present

