---
- hosts: all
  become: yes
  tasks:

  - name: Add user to remote hosts
    user: name=vitalii groups=wheel shell=/bin/bash password=12345

  - name: Add SSH keys to remote hosts
    authorized_key: user=vitalii key="{{ lookup('file', "/home/vitalii/.ssh/id_rsa.pub") }}"
