---
- name: Install Zabbix Agent
  hosts: zabbix_agent
  become: yes

  vars:
    zbx_srv: 10.26.0.182
    centos7_link: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm

  roles:
    - zabbix.agent

